### ISSUE TITLE
Welcome to Study Groups!

### ISSUE THREAD

**Issue by auremoser** [trustodia/studyGroup#1]
Hello @trustodia !

Thanks for your interest in the [Mozilla Science Lab](https://mozillascience.org/), it's great to hear you're building a [Study Group](https://github.com/mozillascience/studygroup).

My name is [Aurelia](https://mozillascience.org/u/auremoser) and I work at the Mozilla Science Lab, a group building projects/programs globally to support open research and citizen science, including the Study Groups project. Just wanted to introduce myself as a resource, and answer any questions you might have.

Feel free to:
- review our new [Study Group Orientation Guide](https://mozillascience.github.io/study-group-onboarding/) developed by @zee-moz
- [sign up](https://docs.google.com/a/mozillafoundation.org/forms/d/e/1FAIpQLSdtKqAMQnKri-0xLx4hD_fpb000n9czsQd4oo9B2JUgtuIVlg/viewform?c=0&w=1) for our Orientation in January, where we mentor you through the early development of your Study Group
- search for ideas in [the handbook](http://mozillascience.github.io/studyGroupHandbook/)
- build out [a site for your Study Group](https://github.com/mozillascience/studyGroup) and cull from our [library of lessons](https://github.com/mozillascience/studyGroupLessons) for early sessions
- join our monthly study group call (first Fridays, 11AM EST), [subscribe to our mailing list to be notified of those calls](https://mail.mozilla.org/listinfo/msl-study-groups)
- follow our #mozstudy hashtag on twitter, or [our list](https://twitter.com/MozillaScience/lists/mozstudy), ping [@auremoser](https://twitter.com/MozillaScience) to be added

**Join us on our next Study Group Learning call, Friday November 4th, 11am EST**.

Email me at [aurelia@mozillafoundation.org](mailto:aurelia@mozillafoundation.org) with questions, or contact/social media information to join our twitter community and Study Group email listserv. Would love to learn about your lessons, challenges, topic of interest, and events. 

Thanks for reading!

Aurelia
Mozilla Science Lab
[@MozillaScience](https://twitter.com/mozillascience)

**Comment by trustodia** [comment]
thanks Aurelia for hooking me up with this startup. preciate!

**Comment by zee-moz** [comment]
Hi @trustodia,

I'm Zannah Marsh, I work with Aurelia at the Mozilla Science Lab. We're
super excited to have you as part of the program. I also wanted to let you
know about a couple of resources that we hope you'll take advantage of...

If you haven't looked at the new Orientation Guide
https://mozillascience.github.io/study-group-orientation/ Aurelia
mentioned (if you're getting a 404 error, the correct link is here, and the
orientation overs running Group meetings, the super easy setup of your
Study Group website, collaborating online using GitHub, an introduction to
open research practice, and more). *Also, *we’ll be running an online
Orientation-- a series of 4 meetings, one per week -- for new Group Leads
starting next month (November!) and also in January of 2017. It’s a great
opportunity to meet, network, and share ideas with other Groups.  If you’re
interested in joining us, let us know by filling out this form.
https://docs.google.com/a/mozillafoundation.org/forms/d/e/1FAIpQLSdtKqAMQnKri-0xLx4hD_fpb000n9czsQd4oo9B2JUgtuIVlg/viewform?c=0&w=1

There are Study Groups all around the world! _We hope you'll visit our
online Gitter Chat https://gitter.im/mozillascience/studyGroup_\* (you can
sign in with GitHub, or using a Twitter ID) to meet other Study Group
members and share resources and ideas.\* If you'd like to say hello, please
introduce yourself on the chat, tell us where you are, and what you're
planning for your Study Group.

Hope to see you on the Gitter chat soon, and in the orientation sessions!
Thanks!
Zannah
